### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by barbalex** [jonathanepollack/gulp-minify-html#20]
When running gulp-minify-html I'm getting this error:

    PS C:\Users\Alexander\artendb> gulp prod
    request:  couchapp push http://user:password@127.0.0.1:5984/artendb
    [10:36:30] Using gulpfile ~\artendb\gulpfile.js
    [10:36:30] Starting 'prod'...
    [10:36:30] Starting 'browserify'...
    [10:36:30] Running 'bundle'...
    [10:36:30] Finished 'prod' after 23 ms
    [10:36:33] Finished 'bundle' in 2.57 s
    [10:36:33] Finished 'browserify' after 2.59 s
    [10:36:33] Starting 'prod_build_style'...
    [10:36:33] Starting 'prod_build_src'...
    [10:36:33] Starting 'prod_build_html'...
    C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\lib\helpers.js:82
      return !!~list.inline.indexOf(element.name);
               ^
    RangeError: Maximum call stack size exceeded
        at String.replace (native)
        at Helpers.text (C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\lib\helpers.js:223:3
    1)
        at enter (C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\lib\minimize.js:120:45)
        at reduce (C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\lib\minimize.js:106:33)
        at C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\node_modules\async\lib\async.js:27
    2:13
        at iterate (C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\node_modules\async\lib\as
    ync.js:149:13)
        at C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\node_modules\async\lib\async.js:16
    0:25
        at C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\node_modules\async\lib\async.js:27
    4:17
        at close (C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\lib\minimize.js:137:7)
        at C:\Users\Alexander\artendb\node_modules\gulp-minify-html\node_modules\minimize\node_modules\async\lib\async.js:27
    7:13
    PS C:\Users\Alexander\artendb>

my index.html is here: https://github.com/FNSKtZH/artendb/blob/master/_attachments/index_dev.html
this used to work
a few weeks ago I updated from version 0.1.6 to 0.1.8. This is the first time I've minified since.
I updated to 1.0.1 now but the error persists.

**Comment by KilpiBan** [comment]
Having the exact same problem here. You can bypass this by running gulp using
```
node --stack-size=25600 /usr/local/bin/gulp
```
This, however, is not really feasible.

**Comment by jonathanepollack** [comment]
Sorry for letting this slip. Let me do some checking around today.

**Comment by jonathanepollack** [comment]
This looks like a minimize issue.

You need to bring it up with them, sorry!

**Comment by barbalex** [comment]
done, thanks

**Comment by jonathanepollack** [comment]
:+1:

**Comment by gsong** [comment]
For reference: Moveo/minimize#38
